### PR TITLE
Adding image tool

### PR DESCRIPTION
**Pull request by MarcusMedeiros99**
I made a few insertions to add the feature of adding images.

### CODE REVIEW

**Comment by abhimanusharma** [comment]
@RavishaHesh Can you merge this pull request?

**Comment by RavishaHesh** [comment]
> 
> 
> @RavishaHesh Can you merge this pull request?

There was an issue in this PR. that's why I left it open

**Comment by ThodorisElissaios** [comment]
can you please fix the issue?

**Comment by abhimanusharma** [comment]
@RavishaHesh  I am trying to add a static image using Fabric,js documentation.

```
fabric.Image.fromURL("http://localhost/img/test-image.png" , function(img) {

				fabricObj.add(img.set({
					left: event.clientX - fabricObj.upperCanvasEl.getBoundingClientRect().left,
					top: event.clientY - fabricObj.upperCanvasEl.getBoundingClientRect().top,
					angle: 0,
					opacity: 1
				}).scale(1));
				
				inst.active_tool = 0;
			});
		}
```

Instead of adding a layer of image on existing canvas image, it is replacing pdf canvas completely and replacing with image object added by above method.

This is my target: http://fabricjs.com/interaction-with-objects-outside-canvas

To add clickable/external object on canvas.

**Comment by RavishaHesh** [comment]
Added Image Tool support to the latest version

**Pull request closed without merging**
